export const KEY_GUIS = [
  { id: "aurora", name: "Aurora Glass", desc: "Frosted card with animated gradient border" },
  { id: "terminal", name: "Neon Terminal", desc: "Hacker console with scanline and typing text" },
  { id: "dock", name: "Mobile Dock", desc: "Bottom sheet that slides up, built for phones" },
] as const;
export type KeyGuiId = (typeof KEY_GUIS)[number]["id"];

type Opts = { style: KeyGuiId; origin: string; scriptUrl: string; title: string; accent: string; validatorUrl?: string; getKeyUrl?: string; terminalMessage?: string };

const rgb = (hex: string) => {
  const n = parseInt(hex.replace("#", ""), 16);
  return `${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}`;
};
const q = (s: string) => JSON.stringify(s);

const CORE = (o: Opts) => `--// ${o.title} key system — generated by ARIO SCRIPTS
local CONFIG = {
  TITLE = ${q(o.title)},
  VALIDATE = ${q(o.validatorUrl || (o.origin + "/api/public/keys/validate?key="))},
  GET_KEY = ${q(o.getKeyUrl || (o.origin + "/keys"))},
  SCRIPT_URL = ${q(o.scriptUrl)},
  SAVE_FILE = "ario_key.txt",
  ACCENT = Color3.fromRGB(${rgb(o.accent)}),
}
local Players, TweenService, UIS, Http = game:GetService("Players"), game:GetService("TweenService"), game:GetService("UserInputService"), game:GetService("HttpService")
local player = Players.LocalPlayer
local guiParent = (gethui and gethui()) or game:GetService("CoreGui")
local function clean(k) return (tostring(k or ""):gsub("[%s\\"'\`]", "")):upper() end
local function request(url)
  local fn = (syn and syn.request) or (http and http.request) or http_request or request
  if fn then
    local ok, r = pcall(fn, { Url = url, Method = "GET" })
    if ok and r and r.Body then return r.Body end
  end
  local ok, body = pcall(function() return game:HttpGet(url) end)
  return ok and body or nil
end
local function verify(key)
  key = clean(key)
  if not key:match("^ARIO%-%x%x%x%x%x%x%x%x%-%x%x%x%x%x%x%x%x%-%x%x%x%x%x%x%x%x$") then return false, "Wrong key format" end
  local body = request(CONFIG.VALIDATE .. key)
  if not body then return false, "Can't reach server" end
  local ok, data = pcall(function() return Http:JSONDecode(body) end)
  if ok and type(data) == "table" and data.valid == true then return true, data end
  return false, "Invalid or expired key"
end
local function save(k) pcall(function() if writefile then writefile(CONFIG.SAVE_FILE, k) end end) end
local function load() local ok, k = pcall(function() return isfile and isfile(CONFIG.SAVE_FILE) and readfile(CONFIG.SAVE_FILE) end) return ok and k or nil end
local function copyLink() if setclipboard then setclipboard(CONFIG.GET_KEY) return true end return false end
local function run() task.spawn(function() local src = request(CONFIG.SCRIPT_URL) if src then local f = loadstring(src) if f then f() end end end) end
local function tween(o, t, p) TweenService:Create(o, TweenInfo.new(t, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), p):Play() end
local function new(c, p, kids) local i = Instance.new(c) for k, v in pairs(p or {}) do i[k] = v end for _, ch in ipairs(kids or {}) do ch.Parent = i end return i end
local function corner(r) return new("UICorner", { CornerRadius = UDim.new(0, r) }) end
local function drag(handle, frame)
  local dragging, start, pos
  handle.InputBegan:Connect(function(i) if i.UserInputType == Enum.UserInputType.MouseButton1 or i.UserInputType == Enum.UserInputType.Touch then dragging, start, pos = true, i.Position, frame.Position i.Changed:Connect(function() if i.UserInputState == Enum.UserInputState.End then dragging = false end end) end end)
  UIS.InputChanged:Connect(function(i) if dragging and (i.UserInputType == Enum.UserInputType.MouseMovement or i.UserInputType == Enum.UserInputType.Touch) then local d = i.Position - start frame.Position = UDim2.new(pos.X.Scale, pos.X.Offset + d.X, pos.Y.Scale, pos.Y.Offset + d.Y) end end)
end
local saved = load()
if saved and verify(saved) then run() return end
local mobile = UIS.TouchEnabled and not UIS.KeyboardEnabled
local W = mobile and 0.9 or 0
local Screen = new("ScreenGui", { Name = "ArioKey", ResetOnSpawn = false, ZIndexBehavior = Enum.ZIndexBehavior.Sibling, Parent = guiParent })
`;

const SUBMIT = `
local busy = false
local function submit(box, status, onOk)
  if busy then return end busy = true
  status.Text = "Checking key..." status.TextColor3 = Color3.fromRGB(200, 200, 210)
  task.spawn(function()
    local ok, res = verify(box.Text)
    busy = false
    if ok then
      status.Text = "Key accepted — loading" status.TextColor3 = Color3.fromRGB(90, 230, 140)
      save(clean(box.Text)) task.wait(0.6) onOk() run()
    else
      status.Text = res status.TextColor3 = Color3.fromRGB(255, 95, 95)
    end
  end)
end
`;

const AURORA = `${SUBMIT}
local Card = new("Frame", { Size = UDim2.new(W, mobile and 0 or 380, 0, 250), Position = UDim2.fromScale(0.5, 0.5), AnchorPoint = Vector2.new(0.5, 0.5), BackgroundColor3 = Color3.fromRGB(14, 16, 26), BackgroundTransparency = 0.08, Parent = Screen }, { corner(18) })
local stroke = new("UIStroke", { Thickness = 2, Parent = Card })
local grad = new("UIGradient", { Color = ColorSequence.new({ ColorSequenceKeypoint.new(0, CONFIG.ACCENT), ColorSequenceKeypoint.new(0.5, Color3.fromRGB(255,255,255)), ColorSequenceKeypoint.new(1, CONFIG.ACCENT) }), Parent = stroke })
task.spawn(function() while Card.Parent do grad.Rotation = (grad.Rotation + 2) % 360 task.wait() end end)
local Title = new("TextLabel", { Text = CONFIG.TITLE, Font = Enum.Font.GothamBlack, TextSize = 20, TextColor3 = Color3.new(1,1,1), BackgroundTransparency = 1, Position = UDim2.new(0, 20, 0, 16), Size = UDim2.new(1, -60, 0, 24), TextXAlignment = Enum.TextXAlignment.Left, Parent = Card })
new("TextLabel", { Text = "Enter your key to continue", Font = Enum.Font.Gotham, TextSize = 13, TextColor3 = Color3.fromRGB(150,155,175), BackgroundTransparency = 1, Position = UDim2.new(0, 20, 0, 42), Size = UDim2.new(1, -40, 0, 18), TextXAlignment = Enum.TextXAlignment.Left, Parent = Card })
local Close = new("TextButton", { Text = "✕", Font = Enum.Font.GothamBold, TextSize = 16, TextColor3 = Color3.fromRGB(180,180,190), BackgroundTransparency = 1, Position = UDim2.new(1, -40, 0, 14), Size = UDim2.fromOffset(28, 28), Parent = Card })
local Box = new("TextBox", { PlaceholderText = "ARIO-XXXXXXXX-XXXXXXXX-XXXXXXXX", Text = "", ClearTextOnFocus = false, Font = Enum.Font.Code, TextSize = 13, TextColor3 = Color3.new(1,1,1), PlaceholderColor3 = Color3.fromRGB(100,105,125), BackgroundColor3 = Color3.fromRGB(24, 27, 42), Position = UDim2.new(0, 20, 0, 80), Size = UDim2.new(1, -40, 0, 44), Parent = Card }, { corner(12), new("UIStroke", { Color = Color3.fromRGB(45, 50, 75) }) })
local Status = new("TextLabel", { Text = "", Font = Enum.Font.Gotham, TextSize = 12, BackgroundTransparency = 1, Position = UDim2.new(0, 20, 0, 130), Size = UDim2.new(1, -40, 0, 18), TextColor3 = Color3.new(1,1,1), Parent = Card })
local function btn(text, x, primary) return new("TextButton", { Text = text, Font = Enum.Font.GothamBold, TextSize = 14, TextColor3 = Color3.new(1,1,1), AutoButtonColor = true, BackgroundColor3 = primary and CONFIG.ACCENT or Color3.fromRGB(30, 34, 52), Position = UDim2.new(x, x == 0 and 20 or 6, 0, 170), Size = UDim2.new(0.5, -26, 0, 46), Parent = Card }, { corner(12) }) end
local Get, Sub = btn("Get Key", 0, false), btn("Submit", 0.5, true)
local function closeUI() tween(Card, 0.3, { Size = UDim2.new(0, 0, 0, 0) }) task.wait(0.3) Screen:Destroy() end
Get.MouseButton1Click:Connect(function() Status.Text = copyLink() and "Key link copied — paste it in your browser" or CONFIG.GET_KEY Status.TextColor3 = CONFIG.ACCENT end)
Sub.MouseButton1Click:Connect(function() submit(Box, Status, closeUI) end)
Close.MouseButton1Click:Connect(closeUI)
drag(Title, Card)
Card.Size = UDim2.new(0, 0, 0, 0) tween(Card, 0.45, { Size = UDim2.new(W, mobile and 0 or 380, 0, 250) })
`;

const TERMINAL = `${SUBMIT}
local G = Color3.fromRGB(${"${R}"})
local Win = new("Frame", { Size = UDim2.new(W, mobile and 0 or 420, 0, 270), Position = UDim2.fromScale(0.5, 0.5), AnchorPoint = Vector2.new(0.5, 0.5), BackgroundColor3 = Color3.fromRGB(6, 8, 6), Parent = Screen, ClipsDescendants = true }, { corner(8), new("UIStroke", { Color = CONFIG.ACCENT, Thickness = 1.5 }) })
local Bar = new("Frame", { Size = UDim2.new(1, 0, 0, 30), BackgroundColor3 = Color3.fromRGB(14, 18, 14), Parent = Win })
new("TextLabel", { Text = "  root@ario:~/" .. CONFIG.TITLE:lower():gsub("%s", "_"), Font = Enum.Font.Code, TextSize = 13, TextColor3 = CONFIG.ACCENT, BackgroundTransparency = 1, Size = UDim2.new(1, -40, 1, 0), TextXAlignment = Enum.TextXAlignment.Left, Parent = Bar })
local Close = new("TextButton", { Text = "[x]", Font = Enum.Font.Code, TextSize = 14, TextColor3 = Color3.fromRGB(255, 90, 90), BackgroundTransparency = 1, Position = UDim2.new(1, -36, 0, 0), Size = UDim2.fromOffset(32, 30), Parent = Bar })
local Log = new("TextLabel", { Text = "", Font = Enum.Font.Code, TextSize = 13, TextColor3 = CONFIG.ACCENT, BackgroundTransparency = 1, Position = UDim2.new(0, 14, 0, 40), Size = UDim2.new(1, -28, 0, 60), TextXAlignment = Enum.TextXAlignment.Left, TextYAlignment = Enum.TextYAlignment.Top, TextWrapped = true, Parent = Win })
task.spawn(function() local s = "> initializing secure link...\\n> key required. type: get_key or paste below" for i = 1, #s do Log.Text = s:sub(1, i) task.wait(0.015) end end)
local Box = new("TextBox", { PlaceholderText = "$ paste key_", Text = "", ClearTextOnFocus = false, Font = Enum.Font.Code, TextSize = 14, TextColor3 = Color3.new(1,1,1), PlaceholderColor3 = Color3.fromRGB(80, 110, 80), BackgroundColor3 = Color3.fromRGB(12, 16, 12), Position = UDim2.new(0, 14, 0, 110), Size = UDim2.new(1, -28, 0, 40), TextXAlignment = Enum.TextXAlignment.Left, Parent = Win }, { corner(4), new("UIStroke", { Color = CONFIG.ACCENT, Transparency = 0.6 }), new("UIPadding", { PaddingLeft = UDim.new(0, 10) }) })
local Status = new("TextLabel", { Text = "", Font = Enum.Font.Code, TextSize = 12, BackgroundTransparency = 1, Position = UDim2.new(0, 14, 0, 156), Size = UDim2.new(1, -28, 0, 18), TextXAlignment = Enum.TextXAlignment.Left, TextColor3 = Color3.new(1,1,1), Parent = Win })
local function btn(text, x) return new("TextButton", { Text = text, Font = Enum.Font.Code, TextSize = 14, TextColor3 = CONFIG.ACCENT, BackgroundColor3 = Color3.fromRGB(12, 20, 12), Position = UDim2.new(x, x == 0 and 14 or 6, 0, 190), Size = UDim2.new(0.5, -20, 0, 44), Parent = Win }, { corner(4), new("UIStroke", { Color = CONFIG.ACCENT }) }) end
local Get, Sub = btn("> get_key", 0), btn("> execute", 0.5)
local Scan = new("Frame", { Size = UDim2.new(1, 0, 0, 2), BackgroundColor3 = CONFIG.ACCENT, BackgroundTransparency = 0.7, BorderSizePixel = 0, Parent = Win })
task.spawn(function() while Win.Parent do Scan.Position = UDim2.new(0, 0, 0, 0) tween(Scan, 2.2, { Position = UDim2.new(0, 0, 1, 0) }) task.wait(2.3) end end)
local function closeUI() tween(Win, 0.25, { BackgroundTransparency = 1 }) task.wait(0.25) Screen:Destroy() end
Get.MouseButton1Click:Connect(function() Status.Text = copyLink() and "> link copied to clipboard" or ("> " .. CONFIG.GET_KEY) Status.TextColor3 = CONFIG.ACCENT end)
Sub.MouseButton1Click:Connect(function() submit(Box, Status, closeUI) end)
Close.MouseButton1Click:Connect(closeUI)
drag(Bar, Win)
`.replace('local G = Color3.fromRGB(${R})\n', "");

const DOCK = `${SUBMIT}
local Dim = new("Frame", { Size = UDim2.fromScale(1, 1), BackgroundColor3 = Color3.new(0,0,0), BackgroundTransparency = 1, Parent = Screen })
tween(Dim, 0.3, { BackgroundTransparency = 0.45 })
local Sheet = new("Frame", { Size = UDim2.new(mobile and 1 or 0, mobile and 0 or 440, 0, 290), AnchorPoint = Vector2.new(0.5, 1), Position = UDim2.new(0.5, 0, 1, 300), BackgroundColor3 = Color3.fromRGB(16, 18, 28), Parent = Screen }, { corner(24) })
new("Frame", { Size = UDim2.fromOffset(44, 5), Position = UDim2.new(0.5, -22, 0, 10), BackgroundColor3 = Color3.fromRGB(70, 75, 95), Parent = Sheet }, { corner(3) })
local Icon = new("Frame", { Size = UDim2.fromOffset(46, 46), Position = UDim2.new(0, 22, 0, 30), BackgroundColor3 = CONFIG.ACCENT, Parent = Sheet }, { corner(23) })
new("TextLabel", { Text = "🔑", TextSize = 22, BackgroundTransparency = 1, Size = UDim2.fromScale(1, 1), Parent = Icon })
task.spawn(function() while Sheet.Parent do tween(Icon, 0.9, { BackgroundTransparency = 0.35 }) task.wait(0.9) tween(Icon, 0.9, { BackgroundTransparency = 0 }) task.wait(0.9) end end)
new("TextLabel", { Text = CONFIG.TITLE, Font = Enum.Font.GothamBlack, TextSize = 19, TextColor3 = Color3.new(1,1,1), BackgroundTransparency = 1, Position = UDim2.new(0, 80, 0, 32), Size = UDim2.new(1, -140, 0, 22), TextXAlignment = Enum.TextXAlignment.Left, Parent = Sheet })
new("TextLabel", { Text = "Unlock with your free key", Font = Enum.Font.Gotham, TextSize = 13, TextColor3 = Color3.fromRGB(150,155,175), BackgroundTransparency = 1, Position = UDim2.new(0, 80, 0, 54), Size = UDim2.new(1, -140, 0, 18), TextXAlignment = Enum.TextXAlignment.Left, Parent = Sheet })
local Close = new("TextButton", { Text = "✕", Font = Enum.Font.GothamBold, TextSize = 16, TextColor3 = Color3.fromRGB(180,180,190), BackgroundColor3 = Color3.fromRGB(30, 33, 48), Position = UDim2.new(1, -52, 0, 34), Size = UDim2.fromOffset(32, 32), Parent = Sheet }, { corner(16) })
local Box = new("TextBox", { PlaceholderText = "Paste your key", Text = "", ClearTextOnFocus = false, Font = Enum.Font.GothamMedium, TextSize = 15, TextColor3 = Color3.new(1,1,1), PlaceholderColor3 = Color3.fromRGB(100,105,125), BackgroundColor3 = Color3.fromRGB(26, 29, 44), Position = UDim2.new(0, 22, 0, 96), Size = UDim2.new(1, -44, 0, 50), Parent = Sheet }, { corner(14) })
local Status = new("TextLabel", { Text = "", Font = Enum.Font.Gotham, TextSize = 12, BackgroundTransparency = 1, Position = UDim2.new(0, 22, 0, 152), Size = UDim2.new(1, -44, 0, 18), TextColor3 = Color3.new(1,1,1), Parent = Sheet })
local Sub = new("TextButton", { Text = "Unlock", Font = Enum.Font.GothamBold, TextSize = 16, TextColor3 = Color3.new(1,1,1), BackgroundColor3 = CONFIG.ACCENT, Position = UDim2.new(0, 22, 0, 178), Size = UDim2.new(1, -44, 0, 50), Parent = Sheet }, { corner(14) })
local Get = new("TextButton", { Text = "Get Key  →", Font = Enum.Font.GothamBold, TextSize = 14, TextColor3 = CONFIG.ACCENT, BackgroundTransparency = 1, Position = UDim2.new(0, 22, 0, 234), Size = UDim2.new(1, -44, 0, 36), Parent = Sheet })
tween(Sheet, 0.5, { Position = UDim2.new(0.5, 0, 1, mobile and 0 or -20) })
local function closeUI() tween(Sheet, 0.35, { Position = UDim2.new(0.5, 0, 1, 300) }) tween(Dim, 0.35, { BackgroundTransparency = 1 }) task.wait(0.35) Screen:Destroy() end
Get.MouseButton1Click:Connect(function() Status.Text = copyLink() and "Key link copied — open it in your browser" or CONFIG.GET_KEY Status.TextColor3 = CONFIG.ACCENT end)
Sub.MouseButton1Click:Connect(function() submit(Box, Status, closeUI) end)
Close.MouseButton1Click:Connect(closeUI)
`;

export function buildKeyGui(o: Opts) {
  const body = o.style === "aurora" ? AURORA : o.style === "terminal" ? TERMINAL : DOCK;
  let generated = CORE(o) + body;
  if (o.terminalMessage && o.style === "terminal") {
    const safeMessage = o.terminalMessage.replaceAll(String.fromCharCode(13), " ").replaceAll(String.fromCharCode(10), " ").slice(0, 180).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    generated = generated.replace("> initializing secure link...\\n> key required. type: get_key or paste below", "> " + safeMessage + "\\n> key required. type: get_key or paste below");
  }
  return generated;
}
