/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAssistantRouteImport } from './routes/admin.assistant'
import { Route as AdminBadgesRouteImport } from './routes/admin.badges'
import { Route as AdminKeysRouteImport } from './routes/admin.keys'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminRawRouteImport } from './routes/admin.raw'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminScriptsRouteImport } from './routes/admin.scripts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStudioRouteImport } from './routes/admin.studio'
import { Route as AdminDiscordRouteImport } from './routes/admin.discord'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesGameRouteImport } from './routes/games.$game'
import { Route as RawSlugRouteImport } from './routes/raw.$slug'
import { Route as ScriptsIndexRouteImport } from './routes/scripts.index'
import { Route as ScriptsSlugRouteImport } from './routes/scripts.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiPublicKeysValidateRouteImport } from './routes/api/public/keys/validate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssistantRoute = AdminAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKeysRoute = AdminKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRawRoute = AdminRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScriptsRoute = AdminScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudioRoute = AdminStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscordRoute = AdminDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameRoute = GamesGameRouteImport.update({
  id: '/games/$game',
  path: '/games/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const RawSlugRoute = RawSlugRouteImport.update({
  id: '/raw/$slug',
  path: '/raw/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsSlugRoute = ScriptsSlugRouteImport.update({
  id: '/scripts/$slug',
  path: '/scripts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeysValidateRoute = ApiPublicKeysValidateRouteImport.update({
  id: '/api/public/keys/validate',
  path: '/api/public/keys/validate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/keys': typeof KeysRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/raw': typeof AdminRawRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/discord': typeof AdminDiscordRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/discord': typeof AdminDiscordRoute
  '/admin/studio': typeof AdminStudioRoute
  '/admin/discord': typeof AdminDiscordRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/games/$game': typeof GamesGameRoute
  '/raw/$slug': typeof RawSlugRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/api/public/keys/validate': typeof ApiPublicKeysValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/keys': typeof KeysRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/raw': typeof AdminRawRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/games/$game': typeof GamesGameRoute
  '/raw/$slug': typeof RawSlugRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/games': typeof GamesIndexRoute
  '/scripts': typeof ScriptsIndexRoute
  '/api/public/keys/validate': typeof ApiPublicKeysValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/keys': typeof KeysRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/assistant': typeof AdminAssistantRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/keys': typeof AdminKeysRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/raw': typeof AdminRawRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scripts': typeof AdminScriptsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/games/$game': typeof GamesGameRoute
  '/raw/$slug': typeof RawSlugRoute
  '/scripts/$slug': typeof ScriptsSlugRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/api/public/keys/validate': typeof ApiPublicKeysValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/keys'
    | '/leaderboards'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assistant'
    | '/admin/badges'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/raw'
    | '/admin/reports'
    | '/admin/scripts'
    | '/admin/settings'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/studio'
    | '/admin/discord'
    | '/categories/$slug'
    | '/games/$game'
    | '/raw/$slug'
    | '/scripts/$slug'
    | '/u/$username'
    | '/admin/'
    | '/categories/'
    | '/games/'
    | '/scripts/'
    | '/api/public/keys/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/favorites'
    | '/keys'
    | '/leaderboards'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assistant'
    | '/admin/badges'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/raw'
    | '/admin/reports'
    | '/admin/scripts'
    | '/admin/settings'
    | '/admin/themes'
    | '/admin/users'
    | '/categories/$slug'
    | '/games/$game'
    | '/raw/$slug'
    | '/scripts/$slug'
    | '/u/$username'
    | '/admin'
    | '/categories'
    | '/games'
    | '/scripts'
    | '/api/public/keys/validate'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/favorites'
    | '/keys'
    | '/leaderboards'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/assistant'
    | '/admin/badges'
    | '/admin/keys'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/raw'
    | '/admin/reports'
    | '/admin/scripts'
    | '/admin/settings'
    | '/admin/themes'
    | '/admin/users'
    | '/categories/$slug'
    | '/games/$game'
    | '/raw/$slug'
    | '/scripts/$slug'
    | '/u/$username'
    | '/admin/'
    | '/categories/'
    | '/games/'
    | '/scripts/'
    | '/api/public/keys/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  KeysRoute: typeof KeysRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  GamesGameRoute: typeof GamesGameRoute
  RawSlugRoute: typeof RawSlugRoute
  ScriptsSlugRoute: typeof ScriptsSlugRoute
  UUsernameRoute: typeof UUsernameRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
  ApiPublicKeysValidateRoute: typeof ApiPublicKeysValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assistant': {
      id: '/admin/assistant'
      path: '/assistant'
      fullPath: '/admin/assistant'
      preLoaderRoute: typeof AdminAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/keys': {
      id: '/admin/keys'
      path: '/keys'
      fullPath: '/admin/keys'
      preLoaderRoute: typeof AdminKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/raw': {
      id: '/admin/raw'
      path: '/raw'
      fullPath: '/admin/raw'
      preLoaderRoute: typeof AdminRawRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scripts': {
      id: '/admin/scripts'
      path: '/scripts'
      fullPath: '/admin/scripts'
      preLoaderRoute: typeof AdminScriptsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studio': {
      id: '/admin/studio'
      path: '/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AdminStudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discord': {
      id: '/admin/discord'
      path: '/discord'
      fullPath: '/admin/discord'
      preLoaderRoute: typeof AdminDiscordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$game': {
      id: '/games/$game'
      path: '/games/$game'
      fullPath: '/games/$game'
      preLoaderRoute: typeof GamesGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/$slug': {
      id: '/raw/$slug'
      path: '/raw/$slug'
      fullPath: '/raw/$slug'
      preLoaderRoute: typeof RawSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/$slug': {
      id: '/scripts/$slug'
      path: '/scripts/$slug'
      fullPath: '/scripts/$slug'
      preLoaderRoute: typeof ScriptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keys/validate': {
      id: '/api/public/keys/validate'
      path: '/api/public/keys/validate'
      fullPath: '/api/public/keys/validate'
      preLoaderRoute: typeof ApiPublicKeysValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAssistantRoute: typeof AdminAssistantRoute
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminKeysRoute: typeof AdminKeysRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminRawRoute: typeof AdminRawRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScriptsRoute: typeof AdminScriptsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminStudioRoute: typeof AdminStudioRoute
  AdminDiscordRoute: typeof AdminDiscordRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAssistantRoute: AdminAssistantRoute,
  AdminBadgesRoute: AdminBadgesRoute,
  AdminKeysRoute: AdminKeysRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminRawRoute: AdminRawRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScriptsRoute: AdminScriptsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminStudioRoute: AdminStudioRoute,
  AdminDiscordRoute: AdminDiscordRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  KeysRoute: KeysRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  GamesGameRoute: GamesGameRoute,
  RawSlugRoute: RawSlugRoute,
  ScriptsSlugRoute: ScriptsSlugRoute,
  UUsernameRoute: UUsernameRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
  ApiPublicKeysValidateRoute: ApiPublicKeysValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
